[project]
name = "pineapple"
version = "0.1.0"
description = "iOS forensic analysis tool - backend"
readme = "README.md"
authors = [
    { name = "dcdevcode", email = "305354676+dcdevcode@users.noreply.github.com" }
]
requires-python = ">=3.14"
dependencies = [
    "pymobiledevice3>=11.2.1",
    "pywebview>=5.4",
]

[project.scripts]
pineapple = "pineapple.cli:main"
pineapple-gui = "pineapple.app:run"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
